export const SELECT_VIDEO_REQUEST = "VIDEO_REQUEST"
export const SELECT_VIDEO_SUCCESS = "VIDEO_SUCCESS"
export const SELECT_VIDEO_FAIL = "VIDEO_FAIL"
export const SELECT_CLEAR_ERRORS = "CLEAR_ERRORS"

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST"
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS"
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL"

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST"
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL"

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST"
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS"
export const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL"

export const LOAD_COURSES_REQUEST = "LOAD_COURSES_REQUEST"
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS"
export const LOAD_COURSES_FAIL = "LOAD_COURSES_FAIL"

export const PUBLISHED_COURSES_REQUEST = "PUBLISHED_COURSES_REQUEST"
export const PUBLISHED_COURSES_SUCCESS = "PUBLISHED_COURSES_SUCCESS"
export const PUBLISHED_COURSES_FAIL = "PUBLISHED_COURSES_FAIL"

export const LOAD_COURSE_REQUEST = "LOAD_COURSE_REQUEST"
export const LOAD_COURSE_SUCCESS = "LOAD_COURSE_SUCCESS"
export const LOAD_COURSE_FAIL = "LOAD_COURSE_FAIL"

export const SINGLE_COURSE_REQUEST = "SINGLE_COURSE_REQUEST"
export const SINGLE_COURSE_SUCCESS = "SINGLE_COURSE_SUCCESS"
export const SINGLE_COURSE_FAIL = "SINGLE_COURSE_FAIL"

export const PAID_ENROLL_REQUEST = "PAID_ENROLL_REQUEST"
export const PAID_ENROLL_SUCCESS = "PAID_ENROLL_SUCCESS"
export const PAID_ENROLL_FAIL = "PAID_ENROLL_FAIL"

export const CHECK_ENROLL_REQUEST = "CHECK_ENROLL_REQUEST"
export const CHECK_ENROLL_SUCCESS = "CHECK_ENROLL_SUCCESS"
export const CHECK_ENROLL_FAIL = "CHECK_ENROLL_FAIL"

export const FREE_ENROLL_REQUEST = "FREE_ENROLL_REQUEST"
export const FREE_ENROLL_SUCCESS = "FREE_ENROLL_SUCCESS"
export const FREE_ENROLL_FAIL = "FREE_ENROLL_FAIL"

export const EDIT_COURSE_REQUEST = "EDIT_COURSE_REQUEST"
export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS"
export const EDIT_COURSE_FAIL = "EDIT_COURSE_FAIL"

export const GET_LESSONS_REQUEST = "GET_LESSONS_REQUEST"
export const GET_LESSONS_SUCCESS = "GET_LESSONS_SUCCESS"
export const GET_LESSONS_FAIL = "GET_LESSONS_FAIL"

export const POST_LESSONS_REQUEST = "POST_LESSONS_REQUEST"
export const POST_LESSONS_SUCCESS = "POST_LESSONS_SUCCESS"
export const POST_LESSONS_FAIL = "POST_LESSONS_FAIL"

export const STUDENT_COUNT_REQUEST = "STUDENT_COUNT_REQUEST"
export const STUDENT_COUNT_SUCCESS = "STUDENT_COUNT_SUCCESS"
export const STUDENT_COUNT_FAIL = "STUDENT_COUNT_FAIL"

export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST"
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS"
export const GET_COURSE_FAIL = "GET_COURSE_FAIL"
